apiVersion: v1
kind: Secret
metadata:
  name: mysecret1
type: Opaque
stringData:
  username: admin
  password: "12345678"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    env:
      - name: USERTEST
        valueFrom:
          secretKeyRef:
            name: mysecret1
            key: username
      - name: PASSWORDTEST
        valueFrom:
          secretKeyRef:
            name: mysecret1
            key: password
    volumeMounts:
    - name: test
      mountPath: "/opt"
      readOnly: true
  volumes:
  - name: test
    secret:
      secretName: mysecret1
      items:
        - key: username
          path: user.txt
        - key: password
          path: password.txt
